repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python
        additional_dependencies: []

  - repo: local
    hooks:
      - id: odoo_lint_runner
        name: Setup Python
        entry: python scripts/odoo_lint_runner.py
        language: python
        additional_dependencies:
          - pylint-odoo
          - setuptools
        always_run: true
        stages: [pre-commit]

      - id: run-pylint-odoo
        name: Run pylint-odoo
        entry: python -m pylint --load-plugins=pylint_odoo
        language: python
        language_version: python
        additional_dependencies:
          - pylint-odoo
          - setuptools
        args:
          - "--valid-odoo-versions=17.0"
          - "--disable=missing-module-docstring,manifest-required-author,missing-readme,too-few-public-methods,import-error"
        types: [python, xml]
        stages: [pre-commit]

  - repo: https://github.com/OCA/odoo-pre-commit-hooks
    rev: v0.1.6
    hooks:
      - id: oca-checks-odoo-module
      - id: oca-checks-po
        args: ["--fix"]

